baseURL = 'https://RedFocalors.github.io/'
languageCode = 'zh-cn'
title = 'RedTu çš„æŠ€æœ¯åšå®¢'
theme = "PaperMod"

# å¼€å¯ä»£ç é«˜äº®
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    env = "production"
    title = "RedTu çš„å°çªCialloï½(âˆ ãƒ»Ï‰< )âŒ’â˜…"
    description = "ä¸ªäººæˆé•¿è®°å½•ï¼Œåˆ†äº«æŠ€æœ¯å¹²è´§"
    author = "RedTu"
    
    # ç•Œé¢è®¾ç½®
    defaultTheme = "auto" # è‡ªåŠ¨åˆ‡æ¢æš—é»‘/æ˜äº®æ¨¡å¼
    showFullTextContent = false
    displayFullPostContent = false
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true # å¼€å¯ä»£ç ä¸€é”®å¤åˆ¶
    
    # ä¸»é¡µé…ç½®
    [params.homeInfoParams]
        Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢"
        Content = "ä¸“æ³¨äºæŠ€æœ¯å¼€å‘ | æ¢ç´¢çˆ±å¥½è€… | ç»ˆèº«å­¦ä¹ è€…"

    # ç¤¾äº¤é“¾æ¥
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/RedFocalors"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:1137507521@qq.com"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "tags"
        name = "æ ‡ç­¾"
        url = "/tags/"
        weight = 20
    [[menu.main]]
        identifier = "archives"
        name = "å½’æ¡£"
        url = "/archives/"
        weight = 30